### ISSUE TITLE
Issue with Strawberry Perl x64

### ISSUE THREAD

**Issue by aero** [Perl5-Alien/Alien-GSL#1]
Hi,
In case of installing on Windows, it seems that Alien::GSL downloads and installs prebuilt library.
After installing Alien::GSL, I tried to install PDL::Stats module.
but I got the following error messages

CDF.o:CDF.c:(.text+0x188ab): undefined reference to `gsl_cdf_hypergeometric_P'
CDF.o:CDF.c:(.text+0x18bbb): undefined reference to `gsl_cdf_hypergeometric_P'
CDF.o:CDF.c:(.text+0x23731): undefined reference to `gsl_cdf_pascal_P'
CDF.o:CDF.c:(.text+0x239da): undefined reference to `gsl_cdf_pascal_P'
CDF.o:CDF.c:(.text+0x24107): undefined reference to `gsl_cdf_negative_binomial_P
.
.
.

I guess the prebuilt GSL library for windows is only for 32bit.
So it causes linking error with strawberry perl x64's mingw64 compiler.
Now, Do we need two separated library for 32bit and 64bit ?

**Comment by jberger** [comment]
see the comments on #2
