### ISSUE TITLE
Windows support does not work well

### ISSUE THREAD

**Issue by kmx** [Perl5-Alien/Alien-GSL#2]
Hi Joel,

The windows support in Alien::GSL seems to be more a one-time-hack than a systematic approach (but you probably know that).

I see currently 2 issues:

1/ there are precompiled binaries of GSL which I am not able to download. But even if I can dowload them Alien::GSL does not distinguish for what platform (32bit vs 64bit) and for what compiler these prebuild binaries are. And as you can imagine it is not possible to load 32bit gsl into 64bit perl and there are many troubles arising from the fact that prebuild binaries where produced by different compiler than perl itself

2/ I am trying to prepare PDL-extended strawberry perl version with many libraries (including gsl) bundled in it. However Alien::GSL is not able to correctly detect already existing gsl *.dll/*.a/*.h files even if there is gsl-config providing correct values

What I want to suggest is to replace current Windows implementation with a detection based on gsl-config if not found we can try to test some lib/include paths via Devel::CheckLib

I will do the coding I just want to know your opinion whether you'll accept such a change

--
kmx

**Comment by jberger** [comment]
I hope that with the release of 1.00, which is Alien::Base based, that the windows support should improve. If it does not, please open a new bug through which we can craft a configuration based improvement through AB rather than an architecture based one that this ticket was requesting.

**Comment by kmx** [comment]
Alien-GSL-1.00 works fine with strawberry perl PDL edition that comes with precompiled gsl binaries. Thanks.

**Comment by jberger** [comment]
\o/

I would be curious if it works on a more bare perl; can it fetch and build?

**Comment by kmx** [comment]
It also works on "bare" strawberry perl. The only downside is that on my laptop (quadcore) Alien::GSL installation takes 65 minutes. But still huge leap for mankind :)

**Comment by jberger** [comment]
\o/ and :o
